export const Colors = {
  background: "#EEF2F8",
  card: "#FFFFFF",
  cardBorder: "#E8ECF4",
  surface: "#F3F6FC",
  hero: "#3D5BD9",
  heroLight: "#5470E8",
  heroDark: "#2947C4",
  navy: "#1C2B4A",
  primary: "#3D5BD9",
  primaryLight: "#EEF2FF",
  text: "#1A1E2E",
  textSecondary: "#6B7280",
  textMuted: "#9CA3AF",
  success: "#10B981",
  danger: "#EF4444",
  warning: "#F59E0B",
  info: "#3B82F6",
  actionBtn: "#607991",
  inputBg: "#F3F6FC",
  inputBorder: "#DDE3EE",
  overlay: "rgba(28,43,74,0.85)",
  tint: "#3D5BD9",
  tabIconDefault: "#9CA3AF",
  tabIconSelected: "#3D5BD9",
};

export default {
  light: {
    text: Colors.text,
    background: Colors.background,
    tint: Colors.primary,
    tabIconDefault: Colors.tabIconDefault,
    tabIconSelected: Colors.primary,
  },
};
